export enum EventsRound {
  init = 'round:init',
  playerReady = 'round:player:ready',
  start = 'round:start',
  tick = 'round:tick',
  fail = 'round:fail',
  success = 'round:success',
  statusUpdate = 'round:status:update',
  statusUpdateSuccess = 'round:status:update:success',
  statusUpdateError = 'round:status:update:error',
  memberSpawned = 'round:member:spawned',
  memberDragStart = 'round:member:drag:start',
  memberDragEnd = 'round:member:drag:end',
  memberMove = 'round:member:move',
  memberTrapped = 'round:member:trapped',
  memberDropped = 'round:member:dropped',
  memberArrived = 'round:member:arrived',
}
